networks:
  default: { }

volumes:
  mercure_data:
  mercure_config:
  database:

services:
    web:
        image: symfony-supervisor:dev
        build:
            dockerfile: docker/php/Dockerfile
        environment:
            DB_USER: myrtille
            DB_PASSWORD: myrtille
            DB_NAME: myrtille
            DB_SERVICE: database
            DB_PORT: 5432
            MAIL_HOST: maildev
            MAIL_PORT: 1025
            MAIL_STARTTLS: "false"
            MAIL_SMTP_AUTH: "false"
        ports:
            - "8000:80" # Serveur applicatif
        depends_on:
            - database
        volumes:
          - ./src:/var/www/html
          - ./scripts:/var/www/html/scripts

    database:
      image: mariadb:11.3
      command: --max_allowed_packet=64M
      environment:
        MYSQL_DATABASE: myrtille
        MYSQL_ROOT_PASSWORD: myrtille
      volumes:
        - database:/var/lib/mysql:delegated
        - ./docker/dump:/dump
      working_dir: /dump_mysql
      ports:
        - 3355:3306

    maildev:
        image: axllent/mailpit
        networks:
           - default
        ports:
           - "8025:8025"
           - "1025:1025"

    mercure:
      image: dunglas/mercure
      restart: unless-stopped
      environment:
        # Uncomment the following line to disable HTTPS,
        SERVER_NAME: ':80'
        MERCURE_PUBLISHER_JWT_KEY: '10c3fe168e02c1a692a6c77d81d6895f4dbb8f2b31f428d8636025cfa25b1be60da0773f9b934f46b864b51d13196786fada2ba5e658fd3f057d0505cf56d69a61682da58032944d947e330c4b582491d727c6d87b8ac2bf3b7552975b7d9b29115ad3cd21c716279eef5a470071081b6414de12849220e9ca82d9477b3913c13b54e1b1b53a8f9c427dd84eb1abd8d588dff2a20a570c738d9c2f11d9952db713a71e760fec6dec902e1ea26d593e20cd21a6c532c18da6ebe5b89d0772287ec66b5d1e13256149f278139d5efb05fcf6134ebc9ab5d8b671952b9d651fe8638a9642eea32a12f9ad2fa37344f88067e642b6ab22f00636504871715de48ab2'
        MERCURE_SUBSCRIBER_JWT_KEY: '10c3fe168e02c1a692a6c77d81d6895f4dbb8f2b31f428d8636025cfa25b1be60da0773f9b934f46b864b51d13196786fada2ba5e658fd3f057d0505cf56d69a61682da58032944d947e330c4b582491d727c6d87b8ac2bf3b7552975b7d9b29115ad3cd21c716279eef5a470071081b6414de12849220e9ca82d9477b3913c13b54e1b1b53a8f9c427dd84eb1abd8d588dff2a20a570c738d9c2f11d9952db713a71e760fec6dec902e1ea26d593e20cd21a6c532c18da6ebe5b89d0772287ec66b5d1e13256149f278139d5efb05fcf6134ebc9ab5d8b671952b9d651fe8638a9642eea32a12f9ad2fa37344f88067e642b6ab22f00636504871715de48ab2'
        # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
        MERCURE_EXTRA_DIRECTIVES: |
          cors_origins *
      # Comment the following line to disable the development mode
      command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
      ports:
        - "8080:80"
      healthcheck:
        test: ["CMD", "curl", "-f", "https://localhost/healthz"]
        timeout: 5s
        retries: 5
        start_period: 60s
      volumes:
        - mercure_data:/data
        - mercure_config:/config
